'use client';

import { useLayoutEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

const milestones = [
  { date:'SEP 2025 — OCT 2025', company:'IAAIIC', place:'Bengaluru', role:'AI/ML Engineering Intern', logo:'IA', stack:['LLM Evaluation','Prompt Engineering','ML Pipelines','Anomaly Detection'], copy:'Designed and integrated LLM prompts for production systems, built ML pipelines, and improved backend reliability and model consistency.' },
  { date:'JUL 2025 — AUG 2025', company:'Opportive', place:'Remote', role:'Full Stack Development Intern', logo:'OP', stack:['Real-time APIs','Backend Systems','Storage','Architecture'], copy:'Built low-latency APIs and real-time systems while contributing to scalable backend services and distributed application architecture.' },
  { date:'APR 2024 — JUN 2024', company:'Plasmid Innovation', place:'India', role:'AI / Backend Intern', logo:'PI', stack:['TypeScript','Node.js','MongoDB','Microservices'], copy:'Developed LLM-powered backend systems, intelligent routing pipelines, APIs, and microservices.' },
];

export function ExperienceTimeline() {
  const root = useRef<HTMLElement>(null); const fill = useRef<HTMLDivElement>(null);
  useLayoutEffect(() => { gsap.registerPlugin(ScrollTrigger); const ctx = gsap.context(() => { if (fill.current) gsap.fromTo(fill.current, { scaleY: 0 }, { scaleY: 1, ease:'none', scrollTrigger:{ trigger:root.current, start:'top 70%', end:'bottom 65%', scrub:.5 } }); gsap.utils.toArray<HTMLElement>('.milestone-card').forEach((card, index) => gsap.fromTo(card, { opacity:0, x:index % 2 ? 70 : -70, y:32 }, { opacity:1, x:0, y:0, duration:.9, ease:'power3.out', scrollTrigger:{ trigger:card, start:'top 82%' } })); gsap.utils.toArray<HTMLElement>('.milestone-node').forEach(node => gsap.to(node, { boxShadow:'0 0 32px rgba(167,139,250,.95)', repeat:-1, yoyo:true, duration:1.35, scrollTrigger:{ trigger:node, start:'top 86%' } })); }, root); return () => ctx.revert(); }, []);
  return <section id="experience" ref={root} className="section overflow-hidden"><p className="eyebrow mb-7">03 / Experience Timeline</p><h2 className="text-5xl tracking-[-.06em] md:text-7xl">Learning in <span className="text-zinc-500">production.</span></h2><div className="relative mt-20"><div className="absolute bottom-0 left-4 top-0 w-px bg-white/10 md:left-1/2"/><div ref={fill} className="absolute bottom-0 left-4 top-0 w-px origin-top bg-gradient-to-b from-violet-300 via-fuchsia-400 to-violet-700 shadow-[0_0_15px_#9f73ff] md:left-1/2"/>{milestones.map((item,index)=><article key={item.company} className={`milestone-card relative mb-14 pl-12 md:mb-20 md:grid md:grid-cols-2 md:pl-0 ${index % 2 ? '' : 'md:[&>div:first-child]:col-start-2'}`}><div className={`glass relative max-w-xl rounded-2xl p-6 md:p-7 ${index % 2 ? 'md:mr-12' : 'md:ml-12'}`}><div className="absolute -left-[2.15rem] top-7 flex h-8 w-8 items-center justify-center rounded-full border border-violet-200/40 bg-[#0a0614] md:hidden"><span className="h-2 w-2 rounded-full bg-violet-300"/></div><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-violet-200/20 bg-violet-500/10 font-mono text-xs text-violet-100">{item.logo}</div><div><h3 className="text-lg">{item.company}</h3><p className="text-xs text-zinc-500">{item.place}</p></div></div><span className="font-mono text-[9px] tracking-wider text-violet-300">{item.date}</span></div><h4 className="mt-6 text-sm text-zinc-200">{item.role}</h4><p className="mt-3 text-sm leading-6 text-zinc-400">{item.copy}</p><div className="mt-5 flex flex-wrap gap-2">{item.stack.map(tech=><span className="rounded-full border border-white/10 px-2.5 py-1 text-[9px] text-zinc-300" key={tech}>{tech}</span>)}</div></div><div className="milestone-node absolute left-0 top-8 h-8 w-8 -translate-x-[45%] rounded-full border border-violet-100/70 bg-violet-300 shadow-[0_0_18px_rgba(167,139,250,.7)] md:left-1/2"/></article>)}</div></section>;
}
