'use client';

import { useEffect, useRef, useState } from 'react';
import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Check, Github, Linkedin, Mail, Sparkles } from 'lucide-react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import dynamic from 'next/dynamic';
const Scene = dynamic(() => import('./scene').then(module => module.Scene), { ssr: false, loading: () => null });
const ProjectShowcase = dynamic(() => import('./project-showcase').then(module => module.ProjectShowcase), { ssr: false });
const ExperienceTimeline = dynamic(() => import('./experience-timeline').then(module => module.ExperienceTimeline), { ssr: false });
const SkillsGalaxy = dynamic(() => import('./skills-galaxy').then(module => module.SkillsGalaxy), { ssr: false });
const ContactScene = dynamic(() => import('./contact-scene').then(module => module.ContactScene), { ssr: false });
const Certifications = dynamic(() => import('./certifications').then(module => module.Certifications), { ssr: false });
const Statistics = dynamic(() => import('./statistics').then(module => module.Statistics), { ssr: false });

const projects = [
  ['01','AI Infrastructure','DualMind AI','Production-grade comparative AI evaluation platform benchmarking frontier and open-source language models.',['Python','Streamlit','OpenAI API','HuggingFace'],'https://github.com/jaya-sri6/DualMind-AI'],
  ['02','Distributed Systems','Concurrent URL Shortener Service','High-throughput, low-latency URL shortener with authentication, caching, analytics, and observability.',['Go','Redis','PostgreSQL','Prometheus'],'https://github.com/jaya-sri6/Concurrent-URL-Shortener'],
  ['03','Retrieval Augmented Generation','LLM-Based Document Processing System','Enterprise document intelligence for insurance policy analysis with semantic retrieval and contextual reasoning.',['FastAPI','LangChain','GPT-4','React'],'https://github.com/jaya-sri6/LLM-RAG-Based-Document-Processing-System'],
  ['04','Agentic AI','Agentic Last Mile Delivery Coordinator','Multi-agent logistics platform for autonomous disruption management, planning, memory, and explainable reasoning.',['Python','LangChain','ReAct','OpenAI'],'https://github.com/jaya-sri6/Agentic-Last-Mile-Delivery-Coordinator'],
  ['05','AI Applications','AI Interview Simulator','Real-time interview platform with conversational evaluation, session management, and intelligent summaries.',['FastAPI','React','Redis','Docker'],'https://github.com/jaya-sri6/AI-Interview-Simulator'],
  ['06','Backend Infrastructure','Distributed API Gateway','Scalable gateway with JWT authentication, service routing, sliding-window rate limiting, and tracing.',['Java','Spring Boot','Redis','JWT'],'https://github.com/jaya-sri6/Distributed-API-Gateway-with-Authentication-and-Rate-Limiting'],
  ['07','Distributed Computing','Distributed Task Queue System','High-performance asynchronous task processing with worker pools, retries, DLQs, and horizontal scale.',['Go','Redis','Docker'],'https://github.com/jaya-sri6/Distributed-Task-Queue-System-'],
] as const;
const experience = [
  ['SEP 2025 — OCT 2025','IAAIIC · Bengaluru','AI/ML Engineering Intern','Designed production LLM prompts and ML pipelines; improved backend reliability, model consistency, anomaly detection, and evaluation systems.'],
  ['JUL 2025 — AUG 2025','Opportive','Full Stack Development Intern','Built low-latency APIs and real-time systems while improving scalable backend services, storage reliability, and distributed architecture.'],
  ['APR 2024 — JUN 2024','Plasmid Innovation Pvt Ltd','AI / Backend Intern','Developed LLM-powered backends, intelligent routing pipelines, APIs, and microservices with TypeScript, Node.js, and MongoDB.'],
];
const skills = ['LLMs','RAG','LangChain','LangGraph','Multi-Agent Systems','Prompt Engineering','Python','Java','Go','FastAPI','Spring Boot','Node.js','Redis','Kafka','Microservices','Event-Driven Architecture','Distributed Queues','Docker','Kubernetes','AWS','Observability','React','TypeScript','Next.js'];

function Reveal({ children, className='' }: { children: React.ReactNode; className?: string }) { return <motion.div className={className} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-70px' }} transition={{ duration: .65, ease: [.16, 1, .3, 1] }}>{children}</motion.div>; }
function ProjectCard({ project }: { project: typeof projects[number] }) { const [tilt, setTilt] = useState({ x: 0, y: 0 }); const [id, type, name, copy, tags, href] = project; return <motion.a layout href={href} target="_blank" rel="noreferrer" onMouseMove={(e) => { const box = e.currentTarget.getBoundingClientRect(); setTilt({ x: (e.clientY - box.top) / box.height * -7 + 3.5, y: (e.clientX - box.left) / box.width * 7 - 3.5 }); }} onMouseLeave={() => setTilt({ x: 0, y: 0 })} animate={{ rotateX: tilt.x, rotateY: tilt.y }} transition={{ type: 'spring', stiffness: 180, damping: 17 }} className="group glass relative block overflow-hidden rounded-2xl p-6 [transform-style:preserve-3d] md:p-9"><div className="absolute -right-20 -top-20 h-56 w-56 rounded-full bg-violet-500/25 blur-[80px] transition group-hover:bg-fuchsia-400/30"/><div className="relative grid gap-6 md:grid-cols-[.35fr_1fr_.85fr] md:items-end"><span className="font-mono text-xs text-zinc-500">{id}</span><div><p className="mb-3 text-[10px] uppercase tracking-[.15em] text-violet-300">{type}</p><h3 className="text-2xl tracking-[-.045em] md:text-4xl">{name}</h3></div><div><p className="mb-5 text-sm leading-6 text-zinc-400">{copy}</p><div className="flex flex-wrap gap-2">{tags.map(tag => <span key={tag} className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-zinc-300">{tag}</span>)}</div></div></div><ArrowUpRight className="absolute right-6 top-6 text-zinc-500 transition group-hover:text-violet-200" size={17}/></motion.a>; }

export function Portfolio() {
  const root = useRef<HTMLDivElement>(null); const { scrollYProgress } = useScroll(); const heroY = useTransform(scrollYProgress, [0, .24], [0, 145]);
  useEffect(() => { const lenis = new Lenis({ lerp: .08, smoothWheel: true }); let frame = 0; const raf = (time: number) => { lenis.raf(time); frame = requestAnimationFrame(raf); }; frame = requestAnimationFrame(raf); return () => { cancelAnimationFrame(frame); lenis.destroy(); }; }, []);
  useEffect(() => { gsap.registerPlugin(ScrollTrigger); const ctx = gsap.context(() => gsap.utils.toArray<HTMLElement>('.timeline-row').forEach(row => gsap.from(row, { opacity: 0, x: -30, duration: .65, scrollTrigger: { trigger: row, start: 'top 85%' } })), root); return () => ctx.revert(); }, []);
  useEffect(() => { const resumeLink = document.querySelector<HTMLAnchorElement>('a[href^="mailto:jayasriijonnalagadda@gmail.com?subject=Resume"]'); if (resumeLink) { resumeLink.href = '/jayasri-jonnalagadda-resume.pdf'; resumeLink.download = 'Jayasri-Jonnalagadda-Resume.pdf'; } }, []);
  return <main ref={root}><div className="noise"/><nav className="fixed top-0 z-30 flex w-full items-center justify-between px-5 py-5 md:px-10" aria-label="Primary navigation"><a href="#top" className="text-xs font-bold tracking-[.16em]">JAYASRI<span className="text-violet-400">/</span>JJ</a><div className="glass hidden gap-6 rounded-full px-5 py-2 text-[11px] text-zinc-300 md:flex"><a href="#about">About</a><a href="#work">Projects</a><a href="#connect">Contact</a></div><a className="glass flex items-center gap-2 rounded-full px-4 py-2 text-[11px]" href="mailto:jayasriijonnalagadda@gmail.com">Let&apos;s talk <ArrowUpRight size={13}/></a></nav>
    <section id="top" className="relative flex min-h-screen items-center overflow-hidden px-5 md:px-10"><div className="grid absolute inset-0 opacity-50"/><div className="orb -right-48 -top-24 opacity-30"/><Scene/><motion.div style={{ y: heroY }} className="relative z-10 max-w-5xl pt-20"><motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .15 }} className="eyebrow mb-7 flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-violet-400 shadow-[0_0_12px_4px_#8b5cf6]"/> AI SYSTEMS ENGINEER · SOFTWARE ENGINEER</motion.div><h1 className="text-[13vw] font-medium leading-[.82] tracking-[-.085em] md:text-[7.8rem]">{'Jayasri'.split('').map((letter, i) => <motion.span key={i} className="inline-block" initial={{ opacity: 0, y: 42, filter: 'blur(8px)' }} animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }} transition={{ duration: .72, delay: .25 + i * .045 }}>{letter}</motion.span>)}<br/><motion.span className="gradient-text" initial={{ opacity: 0, y: 42 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .65 }}>Jonnalagadda.</motion.span></h1><motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .9 }} className="mt-9 max-w-md"><p className="text-base leading-7 text-zinc-300">Building AI Infrastructure, Distributed Systems, and Intelligent Applications.</p><p className="mt-2 text-xs uppercase tracking-[.16em] text-violet-300">Full Stack Developer</p></motion.div><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.08 }} className="mt-8 flex flex-wrap gap-3"><a href="#work" className="rounded-full bg-white px-5 py-3 text-xs font-semibold text-black transition hover:bg-violet-300">View Projects <ArrowDownRight className="ml-1 inline" size={14}/></a><a href="mailto:jayasriijonnalagadda@gmail.com?subject=Resume%20request" className="glass rounded-full px-5 py-3 text-xs">Download Resume</a><a href="#connect" className="glass rounded-full px-5 py-3 text-xs">Contact Me</a></motion.div></motion.div><div className="absolute bottom-7 right-8 z-10 text-[10px] tracking-[.2em] text-zinc-600">SCROLL TO DISCOVER</div></section>
    <section id="about" className="section"><Reveal><p className="eyebrow mb-7">01 / A point of view</p><div className="grid gap-12 md:grid-cols-[1.35fr_.65fr]"><h2 className="text-4xl font-medium leading-[1.05] tracking-[-.055em] md:text-7xl">Intelligence, scalability, reliability, and <span className="text-zinc-500">performance.</span></h2><div className="self-end text-sm leading-7 text-zinc-400">Final-year Computer Science student specializing in AI/ML, building production-grade systems that combine modern AI with scalable software engineering. My work spans RAG, multi-agent orchestration, distributed task processing, observability, backend infrastructure, and cloud-native applications.<br/><br/><span className="text-white">SRM Institute of Science and Technology · graduating May 2026</span></div></div></Reveal></section>
    <Statistics />
    <ExperienceTimeline />
    <ProjectShowcase />
    <SkillsGalaxy />
    <section className="section"><Reveal><p className="eyebrow mb-7">06 / Education</p><div className="glass rounded-2xl p-7 md:p-10"><Check className="mb-12 text-violet-300" size={18}/><h2 className="text-2xl tracking-[-.04em] md:text-4xl">B.Tech Computer Science & Engineering <span className="text-zinc-500">(AI/ML Major)</span></h2><p className="mt-5 text-sm text-zinc-400">SRM Institute of Science and Technology · CGPA 9.5 / 10 · Graduating May 2026</p></div></Reveal></section>
    <footer id="contact" className="relative overflow-hidden border-t border-white/10 px-5 pb-8 pt-28 md:px-10"><div className="orb left-1/4 top-0 opacity-25"/><div className="relative mx-auto max-w-6xl"><p className="eyebrow mb-7">07 / Start a conversation</p><h2 className="max-w-5xl text-5xl leading-[.95] tracking-[-.07em] md:text-8xl">Have a complex<br/><span className="gradient-text">problem in mind?</span></h2><a href="mailto:jayasriijonnalagadda@gmail.com" className="mt-10 inline-flex items-center gap-3 rounded-full bg-white px-6 py-3 text-sm font-medium text-black transition hover:bg-violet-300">jayasriijonnalagadda@gmail.com <ArrowUpRight size={16}/></a><div className="mt-28 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-[10px] tracking-wider text-zinc-500 md:flex-row"><span>© 2026 JAYASRI JONNALAGADDA</span><div className="flex gap-5"><a href="https://github.com/jaya-sri6" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={15}/></a><a href="https://www.linkedin.com/in/jayasri-jonnalagadda-5b86a2379" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={15}/></a><a href="mailto:jayasriijonnalagadda@gmail.com" aria-label="Email"><Mail size={15}/></a></div><a href="https://leetcode.com/u/jayasri_9" target="_blank" rel="noreferrer">LEETCODE ↗</a></div></div></footer>
    <Certifications />
    <ContactScene />
  </main>;
}
