'use client';

import { motion } from 'framer-motion';
import { useState, type CSSProperties } from 'react';
type Skill={name:string;level:string;years:string;projects:string}; type Orbit={label:string;color:string;radius:number;duration:number;skills:Skill[]};
const s=(name:string,projects:string):Skill=>({name,level:'Applied',years:'1+ years',projects});
const orbits:Orbit[]=[
 {label:'AGENTIC AI & LLM ENGINEERING',color:'#d7baff',radius:135,duration:30,skills:[s('LangChain','RAG Platform, Delivery Coordinator'),s('LangGraph','Agentic workflows'),s('RAG','Document Processing System'),s('Prompt Engineering','DualMind AI, IAAIIC'),s('Tool Calling','Agentic systems'),s('Multi-Agent Systems','Delivery Coordinator'),s('LLM Evaluation','DualMind AI'),s('Vector Search','Document Processing System')]},
 {label:'AI INFRASTRUCTURE & BACKEND',color:'#a8bbff',radius:195,duration:55,skills:[s('FastAPI','RAG Platform, Interview Simulator'),s('REST APIs','Backend systems'),s('GraphQL','Full-stack systems'),s('PostgreSQL','URL Shortener'),s('FAISS','Document Processing System'),s('Salesforce Apex','Salesforce AI work'),s('Apex Triggers','Salesforce AI work')]},
 {label:'SOFTWARE ENGINEERING',color:'#f0a8ff',radius:255,duration:80,skills:[s('Python','DualMind, RAG, Delivery'),s('TypeScript','Plasmid Innovation'),s('JavaScript','Full-stack applications'),s('SQL','URL Shortener, Analytics'),s('OOP','Backend engineering'),s('React','RAG, Interview Simulator')]},
 {label:'AI SYSTEMS ENGINEERING',color:'#9ee9db',radius:315,duration:120,skills:[s('Structured Evaluation','DualMind AI'),s('Model Tuning','AI/ML engineering'),s('Observability','URL Shortener, API Gateway'),s('WebSockets','Real-time systems'),s('AI Testing','DualMind AI'),s('Real-time Systems','Interview Simulator, Opportive')]},
 {label:'PRODUCT ENGINEERING',color:'#ffd48c',radius:375,duration:160,skills:[s('Cursor','Product delivery workflows'),s('Claude','AI-assisted engineering'),s('Codex','AI-assisted engineering'),s('VS Code','Daily engineering workflow'),s('Ownership','End-to-end delivery'),s('Fast Iteration','Product engineering'),s('Stakeholder Communication','Internship collaboration'),s('Ambiguity Handling','Systems design')]},
];
export function SkillsGalaxy(){const[active,setActive]=useState<Skill|null>(null);return <section className="section overflow-hidden"><p className="eyebrow mb-7">05 / Skills galaxy</p><h2 className="max-w-4xl text-5xl tracking-[-.06em] md:text-7xl">An orbit of systems <span className="text-zinc-500">thinking together.</span></h2><div className="relative mx-auto mt-14 h-[800px] max-w-[820px] overflow-visible"><div className="absolute left-1/2 top-1/2 z-30 flex h-28 w-28 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-violet-100/60 bg-gradient-to-br from-violet-100 via-violet-400 to-[#260d5b] text-center text-[10px] font-bold tracking-[.16em] text-black shadow-[0_0_58px_16px_rgba(139,92,246,.52)]">AI<br/>CORE</div>{orbits.map(orbit=>{const d=orbit.radius*2;return <div key={orbit.label} className="absolute left-1/2 top-1/2" style={{width:d,height:d,marginLeft:-orbit.radius,marginTop:-orbit.radius}}><div className="absolute inset-0 rounded-full border border-violet-200/55 shadow-[0_0_22px_rgba(167,139,250,.23),inset_0_0_18px_rgba(167,139,250,.13)]" style={{animation:`orbital-spin ${orbit.duration*4}s linear infinite`}}/><span className="absolute left-1/2 -top-7 -translate-x-1/2 whitespace-nowrap text-[10px] font-semibold tracking-[.16em]" style={{color:orbit.color}}>{orbit.label}</span>{orbit.skills.map((skill,index)=>{const start=index/orbit.skills.length*360;const vars={'--orbit-radius':`${orbit.radius}px`,'--orbit-start':`${start}deg`,'--orbit-duration':`${orbit.duration}s`} as CSSProperties;const open=active?.name===skill.name;return <div key={skill.name} className="hud-orbit-node absolute left-1/2 top-1/2 z-20" style={vars}><div className="hud-orbit-node-content"><motion.button onClick={()=>setActive(open?null:skill)} onPointerEnter={()=>setActive(skill)} onPointerLeave={()=>setActive(null)} animate={{scale:open?1.15:1}} transition={{type:'spring',stiffness:220,damping:18}} className="rounded-full border border-white/35 bg-[#100c19]/90 px-3 py-2 text-[10px] font-medium text-white shadow-[0_0_17px_rgba(167,139,250,.24)] backdrop-blur-xl">{skill.name}</motion.button>{open&&<motion.div initial={{opacity:0,scale:.94,y:5}} animate={{opacity:1,scale:1,y:0}} className="absolute left-1/2 top-11 z-50 w-52 -translate-x-1/2 rounded-xl border border-violet-200/30 bg-[#120d1d]/95 p-3 text-left shadow-[0_14px_45px_rgba(0,0,0,.55)] backdrop-blur-xl"><p className="text-[10px] font-semibold text-violet-100">{skill.name}</p><p className="mt-1 text-[9px] text-violet-200">{skill.level} · {skill.years}</p><p className="mt-2 text-[9px] leading-4 text-zinc-300">{skill.projects}</p></motion.div>}</div></div>})}</div>})}<p className="absolute bottom-2 left-1/2 -translate-x-1/2 whitespace-nowrap text-[10px] tracking-[.14em] text-zinc-500">HOVER A NODE TO INSPECT ITS ORBIT</p></div></section>}
